-- MySQL Script generated by MySQL Workbench
-- 01/04/21 20:49:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clinicamedica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinicamedica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinicamedica` DEFAULT CHARACTER SET utf8 ;
USE `clinicamedica` ;

-- -----------------------------------------------------
-- Table `clinicamedica`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicamedica`.`telefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `tel1` VARCHAR(11) NOT NULL,
  `tel2` VARCHAR(11) NULL,
  `cel1` VARCHAR(11) NOT NULL,
  `cel2` VARCHAR(11) NULL,
  PRIMARY KEY (`idTelefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicamedica`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicamedica`.`endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `cidade` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicamedica`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicamedica`.`agenda` (
  `idAgenda` INT NOT NULL AUTO_INCREMENT,
  `horario` DATETIME NOT NULL,
  `dia` DATE NOT NULL,
  PRIMARY KEY (`idAgenda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicamedica`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicamedica`.`login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `privilegio` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicamedica`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicamedica`.`pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoa`),
  CONSTRAINT `telefone_idTelefone`
    FOREIGN KEY ()
    REFERENCES `clinicamedica`.`telefone` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `endereco_idEndereco`
    FOREIGN KEY ()
    REFERENCES `clinicamedica`.`endereco` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `agenda_idAgenda`
    FOREIGN KEY ()
    REFERENCES `clinicamedica`.`agenda` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `login_idLogin`
    FOREIGN KEY ()
    REFERENCES `clinicamedica`.`login` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicamedica`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicamedica`.`medico` (
  `idMedico` INT NOT NULL AUTO_INCREMENT,
  `crm` VARCHAR(10) NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMedico`),
  CONSTRAINT `pessoa_idPessoa`
    FOREIGN KEY ()
    REFERENCES `clinicamedica`.`pessoa` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicamedica`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicamedica`.`paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `tipoSanguineo` VARCHAR(3) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `dataNascimento` DATETIME NOT NULL,
  PRIMARY KEY (`idPaciente`),
  CONSTRAINT `pessoa_idPessoa`
    FOREIGN KEY ()
    REFERENCES `clinicamedica`.`pessoa` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicamedica`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicamedica`.`consulta` (
  `idConsulta` INT NOT NULL AUTO_INCREMENT,
  `realizada` TINYINT(1) NOT NULL,
  `sintoma` VARCHAR(245) NULL,
  `tratamento` VARCHAR(245) NULL,
  `observacao` VARCHAR(245) NULL,
  PRIMARY KEY (`idConsulta`),
  CONSTRAINT `agenda_idAgenda`
    FOREIGN KEY ()
    REFERENCES `clinicamedica`.`agenda` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
